### ISSUE TITLE
Unexpected program halt

### ISSUE THREAD

**Issue by asura6** [roseengineering/teensylc-baremetal#1]
Fantastic job allowing bare-metal programming on the Teensy LC. I believe I have however encountered an issue.

This simple LED-toggle code works fine for me:

    #include "MKL26Z4.h"
    
    #define LED  (1U << 5)
    
    int main(void)
    {
        SIM->SCGC5 = SIM_SCGC5_PORTC_MASK;
        PORTC->PCR[5] = PORT_PCR_MUX(1U);
        PTC->PDDR |= LED;
        PTC->PSOR |= LED;
    } 

If I include a loop which turns off the LED after 10000 iterations:

    #include "MKL26Z4.h"
    
    #define LED  (1U << 5)
    
    int main(void)
    {
        SIM->SCGC5 = SIM_SCGC5_PORTC_MASK;
        PORTC->PCR[5] = PORT_PCR_MUX(1U);
        PTC->PDDR |= LED;
        PTC->PSOR = LED;
    
        int i = 0;
        while(1) {
            if (i == 10000) {
                PTC->PCOR = LED;
                i = 0;
            }
            i++;
        }
    }

The LED will stay on indefinitely and never turn off, even though it should when i == 10000

If I change the number of iterations before the LED shuts off, to for example i == 1000
I see that the LED turns OFF very shortly after running the program. This seem to indicate that there is some issue involving the time. Watchdog perhaps?

Do you have any idea regarding this peculiar behavior? I would really like to be able to program the Teensy-LC on a low level and not using the arduino library.

**Comment by KC7NOA** [comment]
Hope George is responding ... im trying to find out whom this author is. I would like to contact him.

**Comment by asura6** [comment]
I came to a solution by writing my own Teensy-initialization.
Have a look at https://github.com/asura6/teensy-lc-from-scratch

**Comment by roseengineering** [comment]
Sorry for the delay.   People from Germany came to work and then I had to whiteboard.  Glad you fixed it.  I will definitely look at asura6's code.
